// packages/dynamic-form/DynamicForm.vue
<template>
  <div>
    <slot name="header" />
    <a-form-model
      ref="form"
      :model="_value"
      :rules="_rules"
      v-bind="_formProps"
    >
      <a-form-model-item
        v-for="(field, key) in fields"
        v-show="!field.hidden"
        :key="key"
        :extra="field.desc"
        :label="field.label"
        :prop="key"
        :required="field.required"
      >
        <component
          :is="_inputTypeMap[field.type]"
          v-model="_value[key]"
          v-bind="field.props"
        />
      </a-form-model-item>
      <slot name="footer">
        <a-form-model-item :wrapper-col="{ span: 14, offset: 4 }">
          <a-button
            type="primary"
            @click="submit"
          >
            Create
          </a-button>
          <a-button
            style="margin-left: 10px;"
            @click="resetFields"
          >
            Reset
          </a-button>
        </a-form-model-item>
      </slot>
    </a-form-model>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator'
// eslint-disable-next-line no-unused-vars
import { AntField, Fields } from '@/types/common'
// eslint-disable-next-line no-unused-vars
import { InputTypeMap } from './utils'
// eslint-disable-next-line no-unused-vars
import { FormModel } from 'ant-design-vue'

@Component({
  components: {}
})
export default class DynamicForm extends Vue {
  @Prop({
    type: Object,
    required: true
  })
  readonly fields!: Fields

  @Prop({
    type: Object,

    default () {
      return {}
    }
  })
  readonly value!: any

  @Prop({
    type: Object,

    default () {
      return {
        // formRow: { gutter: 12 },
        // formCol: { span: 6 },
        formItem: {
          labelCol: { span: 6 }, // 共24
          wrapperCol: { span: 16 }
        }
      }
    }
  })
  readonly layout!: Object

  @Prop({
    type: Boolean
  })
  readonly btnLoading!: boolean

  @Prop({
    type: Function
  })
  readonly onValuesChange: ((props: Vue, fields: AntField) => void) | undefined

  get _value () {
    return this.value
  }

  set _value (value: any) {
    this.$emit('input', value)
  }

  get _rules () {
    return {}
  }

  get _formProps () {
    return this.$attrs
  }

  get _inputTypeMap () {
    return InputTypeMap
  }

  get _form () {
    return this.$refs.form as FormModel
  }

  public submit () {
    this._form.validate((valid) => {
      if (valid) {
        this.$emit('submit')
      } else {
        console.log('error submit!!')
        return false
      }
    })
  }

  public resetFields () {
    this._form.resetFields()
  }

  public getForm () {
    return this._form
  }
}
</script>

<style lang="less" scoped></style>

// packages/dynamic-form/index.jsx
import './index.css'

const dynamicForm = {
  name: 'epv-dynamic-form',
  props: {
    form: { type: Object, required: true },
    value: { type: Object, required: true }
  },
  computed: {
    _value: {
      get () {
        return this.value
      },
      set (value) {
        console.log('value======================')
        console.log(value) // todo
        console.log('======================')

        this.$emit('input', value)
      }
    }
  },
  methods: {
    onClick (e) {
      console.log('e======================')
      console.log(e) // todo
      console.log('======================')

      this.$emit('click', e)
    }
  },
  render () {
    const { _value, form, onClick } = this
    console.log('_Value======================')
    console.log(_value) // todo
    console.log('======================')

    const Form = _value ? (
      <a-form-model
        model={_value}
        rules={form.rules}
        hideRequiredMark={form.hideRequiredMark}
        labelAlign={form.labelAlign}
        layout={form.layout}
        labelCol={form.labelCol}
        wrapperCol={form.wrapperCol}
        colon={form.colon}
        validateOnRuleChange={form.validateOnRuleChange}
      >
        <a-form-model-item label="Activity name">
          <a-input v-model={_value.name} />
        </a-form-model-item>

        <a-form-model-item label="Activity region">
          <a-input v-model={_value.region} />
        </a-form-model-item>

        <a-form-model-item wrapper-col={{ span: 14, offset: 4 }}>
          <a-button type="primary" onClick={onClick}>
            Create
          </a-button>
          <a-button style="margin-left: 10px;">Cancel</a-button>
        </a-form-model-item>
      </a-form-model>
    ) : (
      ''
    )
    return (
      <div>
        {Form}
        {this._value}
      </div>
    )
  }
}
dynamicForm.install = function (Vue) {
  Vue.component(dynamicForm.name, dynamicForm)
}
export default dynamicForm
